server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://139.129.37.84:3306/test
    username: root
    password: BuDou&123
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 139.129.37.84
      port: 6379
      password: Yt526526
      database: 0

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 暂时关闭 RocketMQ 自动配置，等后续开发兑换模块再开启
spring.autoconfigure.exclude: org.apache.rocketmq.spring.autoconfigure.RocketMQAutoConfiguration
